spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
          batch_versioned_data: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

auth:
  success-redirect-uri: "{baseUrl}/login/oauth2/callback"

# 서버 포트 설정 (Render는 PORT 환경변수 사용)
server:
  port: ${PORT:8080}

# 로깅 레벨 설정
logging:
  level:
    root: info
    org.springframework.web: debug

#jwt secret
app:
  jwt:
    secret: ${JWT_SECRET}
  cors:
    front-path: ${FRONT_URL} #cors front url
